checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        psr2_control_structure_declaration: false
        avoid_superglobals: true
        security_vulnerabilities: true
        no_exit: false
        code_rating: true
        duplication: true
filter:
    paths:
        - src/*
coding_style:
    php: true
build:
    environment:
        php:
            version: 7.3
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
            environment:
                php:
                    version: 7.3