name: "Tests"

on:
  - "push"
  - "pull_request"

jobs:
  tests:

    runs-on: "ubuntu-latest"
    continue-on-error: "${{ matrix.continue-on-error }}"
    strategy:
      matrix:
        include:
          - php-versions: "8.2"
            composer-option: ""
            continue-on-error: false
          - php-versions: "8.3"
            continue-on-error: false
          - php-versions: "8.4"
            composer-option: "--ignore-platform-reqs"
            continue-on-error: true

    steps:
    - uses: "actions/checkout@v4"

    - name: "Setup PHP Action"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-versions }}"
        extensions: "intl, xdebug"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v3"
      with:
        composer-options: "--prefer-dist --no-progress ${{ matrix.composer-option }}"

    - name: "Unit + Integration"
      run: "vendor/bin/phpunit"

    - name: "Mutation tests"
      run: "vendor/bin/infection --min-msi=100 --no-progress --threads=5"
